#!/usr/bin/env bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# git-hooks also wants to be able to call a hook with one argument '--about'
# to output a short string explaining what the hook does.

if [ "$1" = "--about" ]; then
    echo "Hook refusing to commit files in a deteched HEAD state."
    exit 0
fi

# This will do what we want, i.e. return a code != 0 if we're in a detached HEAD state
git symbolic-ref HEAD -q >/dev/null

# Print a helpful explanation if needed
if [ $? -ne 0 ]; then
    echo "Refusing to commit to a detached HEAD!" >&2
    exit 1
fi
