= Usage

== Commands

include::commands/html.adoc[leveloffset=+2]
include::commands/pdf.adoc[leveloffset=+2]
include::commands/yaml.adoc[leveloffset=+2]

== Common Options

[#option-levels-ids]]
=== levels.ids (--levels-ids)

Specify what levels are included in the document structure.


[#option-levels-level-includes]]
=== levels.<level>.includes (--levels-<level>@includes)

Specify what should be included on the <level>.

[#option-levels-level-excludes]
=== levels.<level>.excludes (--levels-<level>@excludes)

Specify what should be excluded on the <level>. This overrides includes.

[#option-magic-titles]
=== magic.titles (--magic-titles)

Titles that should be specially handled. These can be included and/or excluded by using the title name.

[#option-keep-empty-sections]
=== keep.empty.sections (--keep-empty-sections)

By default empty sections will be removed.
By setting this config option to true, empty sections after the include/exclude step, will be kept.

[#option-include-ids]
=== include.ids (--include-ids)
Include these IDs.

[#option-exclude-ids]
=== exclude.ids (--exclude-ids)
Exclude these IDs.

[#option-max-allowed-version]
=== max.allowed.version (--max-allowed-version)

If provided this is the highest version that will be kept in the generated document.

[#option-keep-all-versions]
=== keep.all.versions (--keep-all-versions)

If set all verions of a section with a given ID will be included in the generated document.
Otherwise, only the latest version is kept.
