#!/bin/bash
#
# INSTALL
#
# Description:
# Installs the dev environment needed for CI tools development
#

set -eu

SCRIPT=`basename $0`
VERSION=1.0
DEBUG=0
EXEC=
CITOOLS_ROOT=$(cd `dirname "$0"`; cd ../..; pwd)

GLOBALS="SCRIPT VERSION DEBUG CITOOLS_ROOT"

usage() {
    echo "Usage:"
    echo " $SCRIPT [-h|--help] [-v|--version]"
    echo ""
    echo "options:"
    echo " -h, --help        Output this small usage guide and exit"
    echo " -v, --version     Output version information and exit"
    echo " Running the script without arguments will perform the install."
}

version() {
    echo "$SCRIPT from Zenterio -- version $VERSION"
}

print_var_list() {
    for var in $@;do
        echo "$var=${!var}"
    done
}

ARGS=$(getopt -o hv -l "help,version,debug" -n "$SCRIPT" -- "$@");

if [ $? -ne 0 ]; then
    usage
    exit 2
fi

eval set -- "$ARGS";

while true; do
    case $1 in
        -h|--help)
            shift;
            usage
            exit 0;
            ;;
        -v|--version)
            shift;
            version;
            exit 0;
            ;;
        --debug)
            shift;
            DEBUG=1
            EXEC=echo
            ;;
        --)
            shift;
            break;
            ;;
    esac
done

if [ $DEBUG -ne 0 ]; then
    print_var_list "$GLOBALS"
fi

init_git() {
    $EXEC pushd $CITOOLS_ROOT
    $EXEC git submodule init
    $EXEC git submodule update
    $EXEC popd
}

init_git

exit 0
