#!/usr/bin/env bash
set -e

. "${srcdir=.}/init.sh"

test_run_checksum() {
    print_test_name
    local cmd="${ZFTRACE} -s TEST_ROOT_DIR -m -o output/checksum.report ${SCRIPT_DIR}/cat_files ${DATA_DIR}/files"
    TEST_ROOT_DIR="${TEST_ROOT_DIR}" ${cmd} 2>&1 > /dev/null || fail_ "${cmd} does not work"

    strip_report output/checksum.report

    diff --ignore-space-change ${DATA_DIR}/checksum.report output/checksum.report > check.log ||
        { cat check.log; fail_ "report did not look as expected."; }
}

test_run_checksum
