#!/usr/bin/env bash
set -e

. "${srcdir=.}/init.sh"

test_ignored_reported() {
    print_test_name
    local cmd="${ZFTRACE} -s TEST_ROOT_DIR -i ${DATA_DIR}/match_on_file_2.txt \
         -o output/ignored.report -q output/ignored.ignored ${SCRIPT_DIR}/cat_files \
         ${DATA_DIR}/files"
    TEST_ROOT_DIR="${TEST_ROOT_DIR}" ${cmd} 2>&1 >> check.log ||
        { cat check.log; fail_ "${cmd} does not work"; }

    strip_report output/ignored.report
    strip_report output/ignored.ignored

    diff --ignore-space-change ${DATA_DIR}/ignored.report output/ignored.report >> check.log ||
        { cat check.log; fail_ "report did not look as expected."; }

    diff --ignore-space-change ${DATA_DIR}/ignored.ignored output/ignored.ignored >> check.log ||
        { cat check.log; fail_ "report did not look as expected."; }
}


test_ignored_reported

exit 0
