#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# git-hooks also wants to be able to call a hook with one argument '--about'
# to output a short string explaining what the hook does.

if [ "$1" = "--about" ]; then
    echo "Sample hook refusing to commit files ending with a digit."
    exit 0
fi

if [ $(git diff --cached --name-only --diff-filter=A | grep -e '[0-9]$') ]; then
    echo "No files ending with digits!" >&2
    exit 1
fi
