#!/bin/bash

# $1 - box_name
latest_version() {
    local box_name="$1"
    all_versions "${box_name}" | tail -1
}

# $1 - box_name
next_version() {
    local box_name="$1"
    local current_version; current_version=$(latest_version "${box_name}")
    echo "$((current_version+1))"
}

# $1 - box_name
all_versions() {
    local box_name="$1"
    curl -s -X GET "https://vagrant.zenterio.lan/${box_name}/metadata.json" | jq '.versions[]["version"]' --raw-output | sort --version-sort
}

# $1 - username
# $2 - password
# $3 - vagrant_box_file
# $4 - full_box_name
# $5 - box_name
# $6 - provider
# $7 - box_version
upload() {
    local username=$1
    local password=$2
    local vagrant_box_file=$3
    local full_box_name=$4
    local box_name=$5
    local provider=$6
    local box_version=$7
    local md5_checksum; md5_checksum=$(md5sum "${vagrant_box_file}" | awk '{print $1}')
    local sha1_checksum; sha1_checksum=$(shasum -a 1 "${vagrant_box_file}" | awk '{ print $1 }')
    curl -u"${username}:${password}" -T "${vagrant_box_file}" \
        --header "X-Checksum-MD5:${md5_checksum}" \
        --header "X-Checksum-Sha1:${sha1_checksum}" \
        "https://vagrant.zenterio.lan/artifactory/vagrant-local/${full_box_name};box_name=${box_name};box_provider=${provider};box_version=${box_version}"
}
