
.PHONY: help
help:
	@echo
	@echo "Usage make <target> <args> -jN"
	@echo ""
	@echo ""
	@echo " Building:"
	@echo "  image            Build all images"
	@echo ""
	@echo " Building a specific image:"
	@echo "  image_<image>    Build a specific image"
	@echo ""
	@echo " Additional flags can be passed to docker build using DOCKER_BUILD_FLAGS"
	@echo ""
	@echo " Testing:"
	@echo "  check            Run lint and test for all images"
	@echo "  test             Run all fast tests for all images"
	@echo "  lint             Run lint for all images"
	@echo "  systest          Run all longer running tests for all images"
	@echo ""
	@echo " Testing a specific image:"
	@echo "  test_<image>     Run test for a specific image"
	@echo "  lint_<image>     Run lint for a specific image"
	@echo "  systest_<image>  Run all longer running tests for a specific image"
	@echo ""
	@echo " Tag:"
	@echo "  tag              Tags the current latest images with the tag specified in IMAGE_TAG"
	@echo ""
	@echo " Tag a specific image:"
	@echo "  tag_<image>      Tags a specific image with the tag specified in IMAGE_TAG"
	@echo "                   make tag_abs.u14 IMAGE_TAG=MY_TAG"
	@echo ""
	@echo " Publishing:"
	@echo "  push             Push all images to the configured docker registry"
	@echo "                   Requires DOCKER_REGISTRY_USERNAME and DOCKER_REGISTRY_PASSWORD variables to be specified"
	@echo ""
	@echo " Publishing a specific image:"
	@echo "  push_<image>     Push a specific image to the configured docker registry"
	@echo "                   Requires DOCKER_REGISTRY_USERNAME and DOCKER_REGISTRY_PASSWORD variables to be specified"
	@echo ""
	@echo " Clean:"
	@echo ""
	@echo "  clean            Cleans the build directory"
	@echo "  cleanup          Cleans the docker images for the specified IMAGE_TAG (default latest)"
	@echo "                   If IMAGE_TAG is latest clean is also called"
	@echo ""
	@echo " Testing the make system:"
	@echo " NOOP=y            NOOP=y can be used together with any target to list which commands"
	@echo "	                  that would be run"
	@echo ""
	@echo " If you find that a high level target is taking too long to build,"
	@echo " try using the -j flag to run targets in parallel."
	@echo ""
